spring.application.name=auth

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=${DATABASE_PASSWORD:sptech@2025}
spring.datasource.username=${DATABASE_USERNAME:henry}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/capputeeno_auth}

spring.jpa.hibernate.ddl-auto=update

auth.jwt-secret-key=${JWT_SECRET_KEY:default-secret-key}
auth.jwt-issuer=${JWT_ISSUER:capputeeno-auth-service}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

server.port=0