services:
  postgres:
    image: postgres:16-alpine
    container_name: capputeeno_product_postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - capputeeno_product_pgdata:/var/lib/postgresql/data

volumes:
  capputeeno_product_pgdata: